//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserType
    {
        public int Id { get; set; }
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
    }
}
